openapi: 3.0.0
info:
  title: Nami API Documentation
  description: API Documentation for Nami Foundation
servers:
  - url: https://nami.exchange
    description: Nami Exchange API
paths:
  /api/v3/spot/depth:
    get:
      summary: Martket Depth
      parameters:
        - name: symbol
          in: query
          description: Trading pair symbol
          required: false
          schema:
            type: string
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  bid:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
                  asks:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
      x-tryit-out:
        method: GET
        requestBody:
          content:
            application/json:
              schema: {}
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      example: "ok"
                    bid:
                      type: array
                      items:
                        type: array
                        items:
                          type: number
                    asks:
                      type: array
                      items:
                        type: array
                        items:
                          type: number